### ISSUE TITLE
Render image in backend

### ISSUE THREAD

**Issue by crazyshock** [ghunti/HighchartsPHP#47]
It's possible render image in backend?

example, using it $chart->render('chart'); 
returned for me a code, but, i need an image in backend for generating a pdf.

**Comment by Demonslay335** [comment]
It looks like your best bet, since Highcharts is a client-side rendered chart library, is to use something like PhantomJS to run JavaScript from the server. Highcharts even mentions this on their documents and have an npm package available. This wouldn't be something a simple wrapper library like this could really cover, as it defeats the purpose of it.

https://www.highcharts.com/docs/export-module/render-charts-serverside

*I personally have no experience with PhantomJS or Node.js.

**Comment by ghunti** [comment]
@crazyshock really sorry for the long delay.
@Demonslay335 answer is correct, so I'm closing this one.
Thank you both
